#
# Jekyll Config
# 


# Data Model
collections:
  courses:
    output: true
  trainers:
    output: true
  testimonials:


# Site settings
permalink: :slug
timezone: Asia/Kolkata


# Build settings
source: ./templates
destination: ./_site

