#
# Jekyll Config
# 


# Data Model
collections:
  courses:
    title: Courses
    output: true
  trainers:
    title: Trainers
    output: true
  testimonials:
    title: Testimonials


# Site settings
permalink: :slug
timezone: Asia/Kolkata
markdown_ext: "markdown,mkdown,mkdn,mkd,md,liquid"


# Build settings
source: ./templates
destination: ./_site

