#
# Jekyll Config
# 


# Data Model
collections:
  courses:
    title: Courses
    output: true
  events:
    title: Events
    output: true
  trainers:
    title: Trainers
    output: true
  testimonials:
    title: Testimonials
  clients:
    title: Clients
  articles:
    title: Articles
    output: true


# Defaults
defaults:
  -
    scope:
      path: "_courses"
      type: "courses"
    values:
      layout: "course"
  -
    scope:
      path: "_events"
      type: "events"
    values:
      layout: "event"
  -
    scope:
      path: "_trainers"
      type: "trainers"
    values:
      layout: "trainer"
  -
    scope:
      path: "_articles"
      type: "articles"
    values:
      layout: "article"


# Site settings
name: Pipal Academy
permalink: :slug
timezone: Asia/Kolkata
baseurl: ""


# Build settings
source: ./templates
destination: ./_site
keep_files:
  - build
  - js
  - img
markdown_ext: "markdown,mkdown,mkdn,mkd,md,liquid"

